Plot running times
The-OpenROAD-Project/OpenROAD-flow-scripts pull request #1211
Opened 2023-07-08 15:18 UTC by oharboe

I was hoping to plot detailed routing time as a function of area, but so far this script has been useful to generate various test-cases(segfaults or detailed routing errors), so I thought it would be useful to share.

2023-07-11 17:45 UTC, oharboe commented
@maliberty The first commit is in master already, so this PR has only the utility script

2023-07-11 18:26 UTC, maliberty commented on flow/util/plot-running-times.py
> +        pattern = r'^5_2_TritonRoute\s+(\d+)$'
Now 5_2_route.log

2023-07-11 19:22 UTC, oharboe commented on flow/util/plot-running-times.py
> +        pattern = r'^5_2_TritonRoute\s+(\d+)$'
Fixed

2023-07-17 05:30 UTC, oharboe commented
@maliberty Good to go.

2023-07-17 16:36 UTC, maliberty requested changes
Sorry I reviewed but forgot to hit submit.

Are all the non-plotting changes intended here?

2023-07-17 16:36 UTC, maliberty commented on flow/util/plot-running-times.py
> +import subprocess
This script is specific to mock array. It should therefore be in the design dir

2023-07-17 16:40 UTC, oharboe commented
> Sorry I reviewed but forgot to hit submit.
> 
> Are all the non-plotting changes intended here?

Those are already in master.

2023-07-17 16:48 UTC, maliberty approved these changes

2023-07-17 16:48 UTC, merged