use setup/hold violations from json
The-OpenROAD-Project/OpenROAD-flow-scripts pull request #1230
Opened 2023-07-13 15:37 UTC by gadfort

While looking through the metrics I noticed that the setup and hold violation counts in the metrics do not match the ones reported by STA.
This change moves the regexed answer which is binary and replaces it with the correct counts from sta.

There will likely need to be an update to all the metrics to account for this change.

2023-07-13 15:52 UTC, maliberty requested changes
I only see the removal of the metrics not the moving or fixing...

2023-07-13 15:57 UTC, gadfort commented
@maliberty those two tags are already captured in `merge_jsons` above, this removed lines were actually overwriting the correct answers with a different answer.
GCD forexample, has 23 failing setup paths, but gets reported as 1

2023-07-13 16:15 UTC, maliberty commented
@vvbandeira please make any needed metrics updates.  I'll leave this for you to approve & merge.

2023-07-17 15:58 UTC, vvbandeira commented
Replaced by #1239, which includes metrics updates for public and private PDKs to make CI happy.

2023-07-17 15:58 UTC, closed without merging