[Docs] Link to colab notebooks
The-OpenROAD-Project/OpenROAD-flow-scripts pull request #1373
Opened 2023-08-17 03:07 UTC by luarss

@dralabeing @vvbandeira  Link to colab notebooks (ORFS flow + Autotuner flow)

2023-08-17 15:56 UTC, dralabeing commented on docs/toc.yml
>    title: Flow Tutorial
Can you create a separate tutorial for the Colab based execution of GCD under Tutorials? The title says Flow Tutorial. The title should be something like "Running the OpenROAD flow in Google Colab"

2023-08-17 15:57 UTC, dralabeing commented on docs/tutorials/Notebooks.md
> +1. OpenROAD-flow-scripts Autotuner flow [[link](https://colab.research.google.com/drive/1wye0osn34YVWPvTrfBTftjOfGOtF3ABe)]
Numbering. Great to see AutoTuner as part of colab @luarss

2023-08-17 15:58 UTC, dralabeing requested changes
Create a separate tutorial for use of ORFS in Colab as indicated.

2023-08-18 03:26 UTC, luarss commented
![image](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/39641663/c3a79ca4-26c8-4430-b1f6-827d740e099a)

![image](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/39641663/b7d24376-d3f9-4579-8729-dbbc54027281)

2023-08-18 12:35 UTC, vvbandeira requested changes
Small nits.

2023-08-18 12:35 UTC, vvbandeira commented on docs/toc.yml
> +    title: Running the OpenROAD flow in Google Colab
```suggestion
    title: Running the OpenROAD Flow in Google Colab
```

2023-08-18 12:35 UTC, vvbandeira commented on docs/tutorials/Notebooks.md
> +## OpenROAD-flow-scripts automated RTL-GDSII flow
```suggestion
## OpenROAD-flow-scripts Automated RTL-GDSII Flow
```

2023-08-18 12:35 UTC, vvbandeira commented on docs/tutorials/Notebooks.md
> +## Autotuner Flow
```suggestion
## AutoTuner Flow
```

2023-08-18 12:35 UTC, vvbandeira commented on docs/tutorials/Notebooks.md
> +Notebook for the OpenROAD-flow-scripts Autotuner flow for `gcd` design in `sky130hd` technology node can be found [here](https://colab.research.google.com/drive/1wye0osn34YVWPvTrfBTftjOfGOtF3ABe).
```suggestion
Notebook for the OpenROAD-flow-scripts AutoTuner flow for `gcd` design in `sky130hd` technology node can be found [here](https://colab.research.google.com/drive/1wye0osn34YVWPvTrfBTftjOfGOtF3ABe).
```

2023-08-18 23:37 UTC, dralabeing commented on docs/tutorials/Notebooks.md
>  OpenROAD-flow-scripts as follows:
Add this a benefit to using Colab: You can collaborate with your team and easily manage  your OpenROAD design project runs using the Google Colab notebook over the cloud. This helps you to make interactive changes to python or tcl scripts and re-run the flow to examine the impact the changes all from the Notebook.

2023-08-18 23:38 UTC, dralabeing requested changes
Add some specific benefits about the use of Google Colab as suggested other than just being a quickstart.

2023-08-25 17:25 UTC, vvbandeira commented on docs/tutorials/Notebooks.md
> +notebook-based cloud providers such as LambdaLabs/ Paperspace.
```suggestion
Notebook-based packaging offers three main benefits:
1. Colab is completely free to use and can be accessed from any web browser.
1. Colab notebooks can be easily shared with others, making it a great 
   tool for teams to collaborate and manage OpenROAD design runs. 
1. The notebook can easily be modified to be used for on-premise servers or 
   notebook-based cloud providers such as LambdaLabs/Paperspace. 
```

2023-08-25 17:25 UTC, vvbandeira commented on docs/tutorials/Notebooks.md
> +Notebook for the automated flow for `gcd` design in `nangate45` technology node can be found [here](https://colab.research.google.com/drive/1bfcvqOnbw8q7FmSONLw8q7-yBVvKsQot).
```suggestion
The notebook for the automated flow for `gcd` design in `nangate45` technology node can be found [here](https://colab.research.google.com/drive/1bfcvqOnbw8q7FmSONLw8q7-yBVvKsQot).
```

2023-08-25 17:25 UTC, vvbandeira commented on docs/tutorials/Notebooks.md
> +Notebook for the OpenROAD-flow-scripts AutoTuner flow for `gcd` design in `sky130hd` technology node can be found [here](https://colab.research.google.com/drive/1wye0osn34YVWPvTrfBTftjOfGOtF3ABe).
```suggestion
The notebook for the OpenROAD-flow-scripts AutoTuner flow for `gcd` design in `sky130hd` technology node can be found [here](https://colab.research.google.com/drive/1wye0osn34YVWPvTrfBTftjOfGOtF3ABe).
```

2023-08-25 17:25 UTC, vvbandeira commented
LGTM, @dralabeing?

2023-08-25 18:07 UTC, dralabeing commented
> LGTM, @dralabeing?

LGTM!

2023-08-25 18:14 UTC, merged