[Docs] clarity in docs
The-OpenROAD-Project/OpenROAD-flow-scripts pull request #1392
Opened 2023-08-25 03:26 UTC by luarss

Addresses these comments @dralabeing

1. In the Setup section here: https://openroad-flow-scripts.readthedocs.io/en/latest/index.html#setup Include a list of OS's that are supported preferably as part of System Requirements or after.
2. This section https://openroad-flow-scripts.readthedocs.io/en/latest/user/BuildWithDocker.html# does not describe building docker using pre-built binaries, only from sources. This is simply mentioned here: https://openroad-flow-scripts.readthedocs.io/en/latest/user/BuildWithPrebuilt.html
image.png
3.  These should say Build Using not With
image.png

Also, Building with Docker using pre-built binaries should be the recommended mode. After this building using docker locally with sources
4. Do not refer to OpenROAD as OpenROAD App. Standardize to OpenROAD for the application and the OpenROAD flow for OpenROAD-flow-scripts. People don't get the app part .
https://openroad-flow-scripts.readthedocs.io/en/latest/user/UserGuide.html#using-the-openroad-app

2023-08-25 04:22 UTC, stefanottili commented
I've been compiling/running OpenRoad (and Klayout) on M1 MacBook since the beginning of 2022.

The only current issue is that the test_mpl2 and openroad executables comipile/link just fine, but throw a runtime error at execution time unless the link command is massaged to have libortools.dylib put at the end.

I see that CI is at compiling on MacOS x86 (without mpl2/par) but it seems it's not running test cases, right ?

Is that the reason Mac is not on the "list of supported" platforms ?

2023-08-25 06:18 UTC, vijayank88 requested changes

2023-08-25 06:18 UTC, vijayank88 commented on docs/user/BuildWithDocker.md
> +Courtesy of Precision Innovations, they have released triweekly
```suggestion
Courtesy of [Precision Innovations](https://precisioninno.com/), they have released triweekly 
```

2023-08-25 12:59 UTC, vvbandeira requested changes

2023-08-25 12:59 UTC, vvbandeira commented on docs/user/BuildWithDocker.md
> +releases of the OpenROAD binaries in Ubuntu and Debian. This greatly
```suggestion
Courtesy of Precision Innovations, they release `.deb` installers of OpenROAD for Ubuntu and Debian on a regular basis. This greatly
```

2023-08-25 12:59 UTC, vvbandeira commented on docs/index.md
> +| RHEL         | `Y` | `-` | `-` | `-` |
```suggestion
| RHEL         | `Y` | `-` | `Y` | `-` |
```

2023-08-25 12:59 UTC, vvbandeira commented on docs/index.md
> +| RHEL         | `Y` | `-` | `-` | `-` |
Docker installation is available anywhere docker can be installed.

2023-08-25 12:59 UTC, vvbandeira commented on docs/user/BuildWithDocker.md
> +releases of the OpenROAD binaries in Ubuntu and Debian. This greatly
The tentative release schedule is daily, however, there are days without merges (e.g., many weekends) and there could be days with more than one release (e.g., critical bug fix). So "a regular basis" is more in-line with reality.

2023-08-25 12:59 UTC, vvbandeira commented on docs/user/BuildWithDocker.md
> +./build_openroad.sh --threads N
I would prefer without the --threads arg. This way if a user clicks on the copy button they can paste directly on the terminal and it would work.

2023-08-25 12:59 UTC, vvbandeira commented on docs/user/BuildWithDocker.md
> +`docker run -it`, telling it to start the prompt `sh`.
I am not sure about this; let's discuss it. But either way `sh` --> `bash`

2023-08-25 13:20 UTC, luarss commented on docs/user/BuildWithDocker.md
> +`docker run -it`, telling it to start the prompt `sh`.
Yes that has been working for my docker setup. You dont need to add the /bin/sh to run it I think

2023-08-25 13:31 UTC, luarss commented
> I've been compiling/running OpenRoad (and Klayout) on M1 MacBook since the beginning of 2022.
> 
> The only current issue is that the test_mpl2 and openroad executables comipile/link, but throw a runtime error at execution time unless the link command is massaged to have libortools.dylib put at the end.
> 
> I see that CI is at compiling on MacOS x86 (without mpl2/par) but it seems it's not running test cases, right ?
> 
> Is that the reason Mac is not on the "list of supported" platforms ?

@stefanottili  Yes I believe you are right. MacOS is not fully supported for modules that depend on `or-tools`. @vvbandeira Should we add a partially supported OS section?

2023-08-25 18:29 UTC, vvbandeira commented
@luarss 
Add a `*` or a footnote on `Y` of the local install for macOS and mention that `par` and `mpl2` are not available at the moment due to an upstream issue with `or-tools`. Docker install is fine with macOS.

2023-08-28 17:38 UTC, vvbandeira requested changes

2023-08-28 17:38 UTC, vvbandeira commented on docs/index.md
> +| macOS*        | `Y` | `-` | `Y` | `-` |
```suggestion
| macOS        | `Y*` | `-` | `Y` | `-` |
```

2023-08-28 17:38 UTC, vvbandeira commented on docs/index.md
> +Docker installation wherever possible.
```suggestion
For macOS, local compilation for the modules `par` and `mpl2` are not
fully supported due to an upstream issue with `or-tools`. We recommend
Docker installation wherever possible.
```

2023-08-28 17:38 UTC, vvbandeira commented on docs/user/BuildWithDocker.md
> +followed by installing the prebuilt binaries for OpenROAD.
```suggestion
We recommend to use a Docker image of a supported OS
and install OpenROAD using the prebuilt binaries from
Precision Innovations. 
```

2023-08-28 17:38 UTC, vvbandeira commented on docs/user/BuildWithDocker.md
> +`docker run -it`, telling it to start the prompt `sh`.
```suggestion
You can start the container in an interactive mode using 
the command below. 
```

2023-08-28 17:38 UTC, vvbandeira commented on docs/user/BuildWithDocker.md
> +docker run -it ubuntu:22.04 sh
```suggestion
docker run -it ubuntu:22.04
```

2023-08-28 17:40 UTC, vvbandeira approved these changes

2023-08-28 17:49 UTC, merged