Update rules
The-OpenROAD-Project/OpenROAD-flow-scripts pull request #1519
Opened 2023-10-02 21:57 UTC by habibayassin

2023-10-09 18:54 UTC, vvbandeira requested changes

2023-10-09 18:54 UTC, vvbandeira commented on .github/workflows/github-actions-update-rules-force.yml
> +          git commit -m "flow: update rules based on new set golden"
```suggestion
          git commit -m "flow: update rules based on new golden reference"
```

2023-10-09 18:54 UTC, vvbandeira commented on .github/workflows/github-actions-update-rules-force.yml
> +          title: "Update rules"
```suggestion
          title: "[BOT] Update rules"
```

2023-10-09 18:54 UTC, vvbandeira commented on .github/workflows/github-actions-update-rules.yml
> +          git commit -m "flow: update rules based on new set golden"
```suggestion
          git commit -m "flow: update rules based on new golden reference"
```

2023-10-09 18:54 UTC, vvbandeira commented on .github/workflows/github-actions-update-rules.yml
> +          title: "Update rules"
```suggestion
          title: "[BOT] Update rules"
```

2023-10-09 18:54 UTC, vvbandeira commented on .github/workflows/github-actions-update-rules.yml
> +      - set-new-golden
Can't we have multiple types in one GHA and check for which type triggered the dispatch to see if we need to use `--overwrite` or not? Or some other kind of mechanism that avoids having two nearly identical GHA files?

2023-10-09 18:54 UTC, vvbandeira commented on flow/util/genRuleFile.py
> +def genRuleFileFunc(design_dir, update, tighten, failing, variant, golden_metrics={}):
```suggestion
def gen_rule_file(design_dir, update, tighten, failing, variant, golden_metrics={}):
```

2023-10-09 18:54 UTC, vvbandeira commented on flow/util/genRuleFile.py
> +def genRuleFileFunc(design_dir, update, tighten, failing, variant, golden_metrics={}):
For consistency

2023-12-30 20:45 UTC, maliberty commented
@habibayassin @vvbandeira still relevant?

2024-02-27 15:47 UTC, vvbandeira commented on .github/workflows/github-actions-update-rules.yml
> +  push:
@habibayassin 
Is push required here or is it from the testing phase?

2024-03-26 14:32 UTC, merged