detailed route: remove ORFS vars that are unused
The-OpenROAD-Project/OpenROAD-flow-scripts pull request #1687
Opened 2023-12-06 07:13 UTC by oharboe

Detailed route allows passing any option directly to the detailed_route openroad command via the DETAILED_ROUTE_ARGS environment variable. This allows config.mk to pass any option to detailed routing and also external tools, like Autotuner.

The ORFS variables that are in detail_route.tcl now are used by the PDK to provide defaults or from config.mk project files.

This commit was written after a discussion about what ORFS should expose and serves as an example of some careful "Bonasai pruning".

This commit follows the principle that simple common usage should be simple, complicated or uncommon use-cases should be possible.

2023-12-06 10:44 UTC, rovinski commented
I think that removing some of these might break the private CI.

2023-12-06 10:55 UTC, oharboe commented
> I think that removing some of these might break the private CI.

Gotit. In which case, those are examples of variables in use, ideally a test-case can be added to public CI. This would both be good for grepping(it is found to be in use) and for testing...

2023-12-06 21:20 UTC, maliberty requested changes

2023-12-06 21:20 UTC, maliberty commented on flow/scripts/detail_route.tcl
> -if { [info exists ::env(dbProcessNode)]} {
Must keep

2023-12-06 21:20 UTC, maliberty commented on flow/scripts/detail_route.tcl
> -if { [info exists ::env(REPAIR_PDN_VIA_LAYER)]} {
Must keep

2023-12-06 21:22 UTC, maliberty commented
I don't see an easy way to setup a meaningful public test.

2023-12-11 20:02 UTC, maliberty approved these changes

2023-12-11 20:02 UTC, merged