Mock array element latency
The-OpenROAD-Project/OpenROAD-flow-scripts pull request #1925
Opened 2024-04-09 19:10 UTC by tspyrou

2024-04-09 19:13 UTC, tspyrou commented
New PR with the metrics code enhanced to capture the clock latency for both the source and the target clocks. From this we can make the element constraints.sdc file appear to have close to the same slack as the flattened version.

2024-04-09 19:16 UTC, oharboe requested changes
I need a sample mock-array/Element constraints.sdc file that shows how to use the information in this report to make meaningful comments.

2024-04-09 19:23 UTC, tspyrou commented
@oharboe I will add one.

2024-04-09 20:33 UTC, tspyrou commented
@oharboe I updated an SDC. The number in it come from analyzing this information in the updated metrics report.
The goal is to make the path inside the element look like the path at the top.
We could change the input delay in the element sdc to match the 50 seen at the top but I did not modify that heuristic.

 ==========================================================================
global route post repair timing report_checks -path_delay min from inputs
--------------------------------------------------------------------------
Startpoint: io_ins_left_3[0] (input port clocked by clock_vir)
Endpoint: ces_2_7.io_ins_down[0]$_DFF_P_
          (rising edge-triggered flip-flop clocked by clock)
Path Group: clock
Path Type: min

  Delay    Time   Description
---------------------------------------------------------
   0.00    0.00   clock clock_vir (rise edge)
 380.00  380.00   clock network delay (ideal)
  50.00  430.00 v input external delay
   0.00  430.00 v io_ins_left_3[0] (in)
  11.06  441.06 v input705/Y (BUFx2_ASAP7_75t_R)
   0.10  441.16 v ces_2_7.io_ins_down[0]$_DFF_P_/D (DFFHQNx3_ASAP7_75t_R)
         441.16   data arrival time

   0.00    0.00   clock clock (rise edge)
 397.76  397.76   clock network delay (propagated)
  10.00  407.76   clock uncertainty
   0.00  407.76   clock reconvergence pessimism
         407.76 ^ ces_2_7.io_ins_down[0]$_DFF_P_/CLK (DFFHQNx3_ASAP7_75t_R)
  13.52  421.28   library hold time
         421.28   data required time
---------------------------------------------------------
         421.28   data required time
        -441.16   data arrival time
---------------------------------------------------------
          19.88   slack (MET)



==========================================================================
global route post repair timing critical path target clock latency max path
--------------------------------------------------------------------------
310.4272

==========================================================================
global route post repair timing critical path target clock latency min path
--------------------------------------------------------------------------
397.7622

==========================================================================
global route post repair timing critical path source clock latency min path
--------------------------------------------------------------------------
380.0000

2024-04-09 22:43 UTC, tspyrou commented
This is what the path looks like at the Element level with the new SDC for hold.
<pre>
==========================================================================
cts final setup_violation_count
--------------------------------------------------------------------------
setup violation count 264

==========================================================================
cts final hold_violation_count
--------------------------------------------------------------------------
hold violation count 0

==========================================================================
cts final report_checks -path_delay max from inputs
--------------------------------------------------------------------------
Startpoint: io_ins_right[63] (input port clocked by clock_vir)
Endpoint: io_outs_up[63]$_DFF_P_
          (rising edge-triggered flip-flop clocked by clock)
Path Group: clock
Path Type: max

  Delay    Time   Description
---------------------------------------------------------
   0.00    0.00   clock clock_vir (rise edge)
 450.00  450.00   clock network delay (ideal)
 225.00  675.00 ^ input external delay
   0.71  675.71 ^ io_ins_right[63] (in)
  12.26  687.97 ^ hold129/Y (BUFx2_ASAP7_75t_R)
  15.23  703.20 ^ input188/Y (BUFx2_ASAP7_75t_R)
   0.78  703.98 ^ io_outs_up[63]$_DFF_P_/D (DFFHQNx2_ASAP7_75t_R)
         703.98   data arrival time

 300.00  300.00   clock clock (rise edge)
 464.96  764.96   clock network delay (propagated)
 -20.00  744.96   clock uncertainty
   0.00  744.96   clock reconvergence pessimism
         744.96 ^ io_outs_up[63]$_DFF_P_/CLK (DFFHQNx2_ASAP7_75t_R)
  -7.48  737.47   library setup time
         737.47   data required time
---------------------------------------------------------
         737.47   data required time
        -703.98   data arrival time
---------------------------------------------------------
          33.50   slack (MET)
</pre>

This is the top level path
<pre>
==========================================================================
cts post-repair setup_violation_count
--------------------------------------------------------------------------
setup violation count 2112

==========================================================================
cts post-repair hold_violation_count
--------------------------------------------------------------------------
hold violation count 2048

==========================================================================
cts post-repair report_checks -path_delay max from inputs
--------------------------------------------------------------------------
Startpoint: io_ins_left_2[60] (input port clocked by clock_vir)
Endpoint: ces_2_7 (rising edge-triggered flip-flop clocked by clock)
Path Group: clock
Path Type: max

  Delay    Time   Description
---------------------------------------------------------
   0.00    0.00   clock clock_vir (rise edge)
 380.00  380.00   clock network delay (ideal)
  50.00  430.00 ^ input external delay
   0.00  430.00 ^ io_ins_left_2[60] (in)
  11.21  441.21 ^ input697/Y (BUFx2_ASAP7_75t_R)
   0.09  441.30 ^ ces_2_7/io_ins_left[60] (Element)
         441.30   data arrival time

 250.00  250.00   clock clock (rise edge)
 317.48  567.48   clock network delay (propagated)
 -10.00  557.48   clock uncertainty
   0.00  557.48   clock reconvergence pessimism
         557.48 ^ ces_2_7/clock (Element)
 425.98  983.46   library setup time
         983.46   data required time
---------------------------------------------------------
         983.46   data required time
        -441.30   data arrival time
---------------------------------------------------------
         542.17   slack (MET)
</pre>

2024-04-09 23:47 UTC, tspyrou commented
@oharboe My last comment about the scripts and constraints.sdc was in error. I deleted it.
write_timing_model is erroneously including the clock source latency into the model which shows up in a massive required hold time. This is why the run fails unable to fix hold. I will look at a workaround and file a bug.  If you look at the above top level hold path you will see the giant library hold time.

2024-04-10 00:16 UTC, tspyrou commented
@oharboe sorry for all of the comments. I also see that the flat run is not a good predictor of the hierarchical run for some reason.   I had used the flat run to get an idea of the latencies. I will try that with the hier run instead.

2024-04-10 01:21 UTC, tspyrou commented
@oharboe I think we can reserve some time when you are here to discuss.
Currently the register to register timing is closing at the top level and it gets stuck trying to close the i/o hold violations.
Its good to separate those variables and the report_metrics here does that.

2024-04-10 15:29 UTC, merged

2024-04-11 15:42 UTC, maliberty commented on flow/scripts/generate_abstract.tcl
> +set_clock_latency -source 0 [all_clocks]
Should sta handle this?  This seems error prone

2024-04-11 15:43 UTC, maliberty commented
Is this generally useful?  I'm not clear what users should do with this information.