asap7/mock-array: switch manual macro placement for mpl2 flow
The-OpenROAD-Project/OpenROAD-flow-scripts pull request #2059
Opened 2024-06-11 20:10 UTC by AcKoucher

Resolve #1928,

Using #2020 to test mpl2 flow for mock-array showed some metrics degradation in both timing and WL caused by a [group of IOs placed in a different location than we see on master](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/2020#issuecomment-2121167498):

```
[ERROR] detailedroute__route__wirelength fail test: 76149.0 <= 73578.0
[ERROR] finish__timing__setup__ws fail test: -78.1376 >= -6.93
[ERROR] finish__timing__wns_percent_delay fail test: -49.411146 >= -10.0
```

When using manual macro placement, when we get to non-random pin placement stage in the flow, PPL has no information about the std cells position - because non of them are placed - so we luckily end up placing the problematic IO group in the center of the right boundary, because PPL uses as reference the center of the design when it finds no placed insts.

However, MPL2 does generate a temporary location for std cells in order to improve macros' orientations. These locations end up been seen by PPL which chooses a different position for the IO group changing upstream results leading to degradation.

A possible solution would be to not skip global placement without IOs when we have constraints for the pins as it is for mock-array. This way, PPL would have a better std cell location data to work with.
Testing this showed that std cells get split based on the arrays' rows and so does the IO group (in the images zooming into the fourth row from bottom to top):

<p float="left">
  <img src="https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/104802710/7a868390-3598-4985-80d1-766f4bb52c3b" width="200" />
  <img src="https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/104802710/b8c50535-0248-437a-a31c-18de9a8a4661" width="200" />
  <img src="https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/104802710/9c97b82b-6378-4aaf-a045-9adcb6a88351" width="200" />
</p>

This improves WR and ws and we get no failures.
```
[INFO] detailedroute__route__wirelength pass test: 63606.0 <= 73578.0
[INFO] finish__timing__setup__ws pass test: 34.7588 >= -6.93
[INFO] finish__timing__wns_percent_delay pass test: 6.875599 >= -10.0
```

Master:
```
[INFO] detailedroute__route__wirelength pass test: 69582.0 <= 73578.0
[INFO] finish__timing__setup__ws pass test: 10.0482 >= -6.93
[INFO] finish__timing__wns_percent_delay pass test: 14.364462 >= -10.0
```

2024-06-11 20:13 UTC, AcKoucher commented
@oharboe FYI

One additional thing:
In this PR the halos generate the exact same placement as we'd get using manual macro placement. It was just a matter of using a more precise value. I made that to exclude the possibility of the macro placement being the actual cause of the degradation we see in your test PR.

2024-06-11 20:14 UTC, AcKoucher commented
@maliberty Is running a separate secure-ci for the global placement without IOs.

2024-06-12 13:28 UTC, oharboe requested changes
Keep manual placement around for testing purposes for now, just in case.

Use export RTLMP_FLOW ?= True (on by default) and then conditionally include manual macro placement.

Once automated macro placement has matured for a while, the manual placement testcase can be deleted.

2024-06-12 16:45 UTC, oharboe commented
I looked at the significant WNS regression:

```
[ERROR] finish__timing__setup__ws fail test: -91.4696 >= -6.93
```

io_lsbs_61 is a pipeliened signal from ces_7_5, i.e. top row that is driven all the way to the lower right corner with only a single flip flop for that entire path.

![image](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/2798822/334e358c-6d23-44db-bf18-bf331f758af0)



![image](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/2798822/8f6cdbd4-dd57-4de6-a916-53512c71a7ec)

2024-06-12 16:59 UTC, oharboe commented
On master, the io_lsbs_* pins are placed in the middle on the right, which improves WNS by ca. 100ps on a clock period of 250ps.

![image](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/assets/2798822/b320328e-bc70-4a1e-9182-9237cc00ea25)

2024-06-12 18:08 UTC, AcKoucher commented
@oharboe The changes here depend on _not skipping global placement without IOs in the flow_ which is skipped on master for mock-array (we skip this stage when we have pin constraints). We'll need another PR for this skipping part. We're running a secure-ci for it separately, but there are some other issues regarding different designs which are being studied.

2024-07-21 19:51 UTC, oharboe commented
@AcKoucher Any news on this one?

2024-07-21 20:35 UTC, maliberty commented
He's waiting on me - I'm nearly done with the problems within problems.

2024-07-31 00:02 UTC, AcKoucher commented
@oharboe Finally this should be good to merge :) I left the manual mpl file as you requested.

2024-07-31 04:10 UTC, maliberty commented
Please merge master and resolve the OR conflict.

2024-07-31 06:24 UTC, oharboe requested changes
Keep manual placement mock-array under CI. For now anyway...

2024-07-31 06:24 UTC, oharboe commented on flow/designs/asap7/mock-array/config.mk
> +  ifeq ($(RTLMP_FLOW), False)
An niggling little thing about ORFS variables is that there are no types... RTLMP_FLOW actually checks for empty and non-empty....

Also, I would like to keep manual placement under CI.

See here on how to do that:

https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/blob/master/flow/designs/asap7/riscv32i-mock-sram/config.mk

1. create designs/asap7/mock-array-manual/config.mk
2. set RTLMP_FLOW to empty
3. include designs/asap7/mock-array/config.mk
4. add the baseline files(make metadata/update_ok/rules, etc.)

2024-07-31 06:24 UTC, oharboe commented on flow/designs/asap7/mock-array/config.mk
> +  ifeq ($(RTLMP_FLOW), False)
Fewer surprises: https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/2208

2024-07-31 12:35 UTC, maliberty commented
> Keep manual placement mock-array under CI. For now anyway...

What is the criteria for ending it?  What is the benefit to keeping it?

2024-07-31 12:45 UTC, oharboe commented
> > Keep manual placement mock-array under CI. For now anyway...
> 
> What is the criteria for ending it? What is the benefit to keeping it?

Is there any other manual placement with abutment test-case?

2024-07-31 13:17 UTC, maliberty commented
> Is there any other manual placement with abutment test-case?

No but is that substantially different from auto placement with abutment?

2024-07-31 13:20 UTC, oharboe commented
> > Is there any other manual placement with abutment test-case?
> 
> No but is that substantially different from auto placement with abutment?

Perhaps not worth it then...

Cost effective testing is always a challenge and important for OpenROAD, since running times are very long.

2024-07-31 18:04 UTC, oharboe approved these changes
Needs an update after #2208 got merged, but otherwise I say merge it. Very nice! :-)

2024-07-31 20:47 UTC, maliberty approved these changes

2024-07-31 21:57 UTC, merged