platforms: ihp-sg13g2: May Update
The-OpenROAD-Project/OpenROAD-flow-scripts pull request #2084
Opened 2024-06-26 06:59 UTC by dnltz

Picked @KrzysztofHerman update script and modified it slightly. Synced files afterwards with this script and added the bondpad manually.

Should we remove metal fill here since KLayout is supposed to do this task?

2024-06-26 07:59 UTC, maliberty commented
Part of the motivation to implement metal fill in OR was to allow future support for timing aware fill.  If fill can be accomplished in OR it might be nice to keep that door open.

2024-06-26 08:01 UTC, maliberty commented on flow/platforms/ihp-sg13g2/fill.json
> +    "layers" : {},
If you do remove fill you should just remove the entire fill and update the config.

2024-06-26 08:31 UTC, dnltz commented
> Part of the motivation to implement metal fill in OR was to allow future support for timing aware fill. If fill can be accomplished in OR it might be nice to keep that door open.

I would let @KrzysztofHerman decide whether OR should fill the core. Maybe Klayout just fills everything else?

2024-06-26 14:21 UTC, maliberty commented
If you require FEOL fill beyond the usual fill cells that would have to be done in KLayout.  I'll wait on this PR for @KrzysztofHerman 's comments

2024-06-27 07:36 UTC, dnltz commented
> If you require FEOL fill beyond the usual fill cells that would have to be done in KLayout. I'll wait on this PR for @KrzysztofHerman 's comments

I'm gonna drop this patch because not adding `USE_FILL` has the same result. BTW `USE_FILL=0` still adds filler cells.

2024-06-27 13:48 UTC, dnltz commented
Latest update.

- Dropped the fill.json patch. #2089 fixes the USE_FILL variable.
- Added a sed command to `flow/Makefile` to proper support `sg13g2.map`. There should be no ORFS specific relative path in the IHP PDK. See conversation here https://github.com/IHP-GmbH/IHP-Open-PDK/pull/151/files

2024-07-01 06:43 UTC, KrzysztofHerman commented
@dnltz since we have to generate very specific filler in FEOL we have to use klayout so in a case of IHP platform lests use this tool for generating all fill cells FEOL+BEOL. 
As for the `sg13g2.map` I have already seen the changes in `.lyt` fila added in our dev branch. If any modifications are to be done we could handle it "on the fly", while running `sg13g2_update.py` script.

2024-07-01 08:24 UTC, dnltz commented
> @dnltz since we have to generate very specific filler in FEOL we have to use klayout so in a case of IHP platform lests use this tool for generating all fill cells FEOL+BEOL. As for the `sg13g2.map` I have already seen the changes in `.lyt` fila added in our dev branch. If any modifications are to be done we could handle it "on the fly", while running `sg13g2_update.py` script.

@KrzysztofHerman I think ORFS should be synced with main and not dev. Therefore, I made this change manually to fix it in a proper way. The current solution is way cleaner ... 

any concerns about this PR?

2024-07-03 15:02 UTC, maliberty commented
Does this contain RAMS as inquired about in https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/discussions/2099 ?

What remains in order to merge this?

2024-07-03 15:15 UTC, KrzysztofHerman commented
@maliberty we are waiting for some fixes in IOCells, after it is ready we can update and merge.

2024-07-03 15:27 UTC, maliberty commented
Do you have an ETA for that?  If it will be a while it might be good to make a separate PR to pull in the RAMs.

2024-07-04 12:21 UTC, dnltz commented
@KrzysztofHerman is this something we could update later? I would like to continue with the other pull-request to finally send ElemRV...

2024-07-05 07:09 UTC, KrzysztofHerman commented
@dnltz since I do not have an ETA for the IOCells we can separate the abovementioned PR's.

2024-07-22 10:48 UTC, maliberty commented
Any eta for this?

2024-07-22 21:06 UTC, maliberty commented
As this PR is proceeding slowly I've opened https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/2171 to merge the RAM related files (only typ corner) to enable the user in #2099

2024-07-25 06:47 UTC, dnltz commented
> As this PR is proceeding slowly I've opened #2171 to merge the RAM related files (only typ corner) to enable the user in #2099

Rebased to master and pinged @KrzysztofHerman to take a look.

2024-07-25 10:19 UTC, KrzysztofHerman commented
@dnltz please go ahead

2024-07-25 16:00 UTC, dnltz commented
@maliberty it failed to build an asap7 design. Still fine?

2024-07-25 16:51 UTC, maliberty commented
> @maliberty it failed to build an asap7 design. Still fine?

Yes

2024-07-25 16:56 UTC, maliberty requested changes

2024-07-25 16:56 UTC, maliberty commented on flow/platforms/ihp-sg13g2/lef/sg13g2_io_notracks.lef
What is the difference between this and flow/platforms/ihp-sg13g2/lef/sg13g2_io.lef ?  Are both required?

2024-07-25 16:56 UTC, maliberty commented on flow/platforms/ihp-sg13g2/sg13g2_update.py
> +download_github_file('ihp-sg13g2/libs.ref/sg13g2_io/gds/sg13g2_io.gds', 'gds')
Why is bondpad_70x70.gds missing?

2024-07-25 16:56 UTC, maliberty commented on flow/platforms/ihp-sg13g2/sg13g2_update.py
> +download_github_file('ihp-sg13g2/libs.ref/sg13g2_io/lef/sg13g2_io_notracks.lef', 'lef')
Why is bondpad_70x70.lef missing?

2024-07-25 16:56 UTC, maliberty commented on flow/platforms/ihp-sg13g2/sg13g2_update.py
> +# GDS
The RM*gds are missing

2024-07-25 16:56 UTC, maliberty commented on flow/platforms/ihp-sg13g2/sg13g2_update.py
> +# LEF
The RM*lef are missing

2024-07-25 16:56 UTC, maliberty commented on flow/platforms/ihp-sg13g2/sg13g2_update.py
> +# LIB
The RM*.lib are missing

2024-07-25 16:56 UTC, maliberty commented on flow/platforms/ihp-sg13g2/sg13g2_update.py
> +# Verilog
The RM*.v are missing from the script.  I also missed importing them so they should be added to this PR.

2024-07-31 08:41 UTC, dnltz commented on flow/platforms/ihp-sg13g2/sg13g2_update.py
> +# GDS
Fixed that. Thanks!

2024-07-31 08:42 UTC, dnltz commented on flow/platforms/ihp-sg13g2/sg13g2_update.py
> +download_github_file('ihp-sg13g2/libs.ref/sg13g2_io/gds/sg13g2_io.gds', 'gds')
bondpad is currently only located in this repo. I think the long-term solution is to generate those cells with Klayout similar to the sealring. So, just a temporarily solution to build chips.

2024-07-31 08:42 UTC, dnltz commented on flow/platforms/ihp-sg13g2/lef/sg13g2_io_notracks.lef
@KrzysztofHerman can be drop the io_notrack LEF file here?

2024-08-05 12:17 UTC, dnltz commented
@maliberty I removed the `sg13g2_io_notracks.lef` file since it has no use case here.

2024-08-05 18:39 UTC, maliberty approved these changes

2024-08-05 20:17 UTC, merged