[Autotuner] Plotting utility
The-OpenROAD-Project/OpenROAD-flow-scripts pull request #2394
Opened 2024-09-29 05:16 UTC by luarss

- Plotting utility
- README

2024-10-10 12:52 UTC, vvbandeira requested changes

2024-10-10 12:52 UTC, vvbandeira commented on docs/user/InstructionsForAutoTuner.md
> +Currently, we support the following metrics:
```suggestion
After running an AutoTuner experiment, you can generate a graph to understand the results better.
The graph will show one of the metrics listed below progression over the execution of the experiment.
```

2024-10-10 12:52 UTC, vvbandeira commented on tools/AutoTuner/src/autotuner/utils/plot.py
> +        default="../../../../../flow/logs/asap7/gcd/test-tune-2024-09-17-12-00-44",
```suggestion
```
Remove hardcoded.
This argument should be required.

2024-10-10 16:58 UTC, vvbandeira commented on docs/user/InstructionsForAutoTuner.md
> +The graph will show one of the metrics listed below progression over the execution of the experiment.
```suggestion
The graph will show the progression of one metric (see list below) over the execution of the experiment.
```

2024-10-10 16:58 UTC, vvbandeira requested changes
Please add a call to this script in the `test_helper.py` so we test this script.

2025-01-11 16:31 UTC, vvbandeira requested changes

2025-01-11 16:31 UTC, vvbandeira commented on flow/test/test_autotuner.sh
> +# fi
Remove?

2025-01-11 16:31 UTC, vvbandeira commented on tools/AutoTuner/src/autotuner/utils/plot.py
> +            continue
Should we keep a list of the files that were not processed so we can print them at the very end in order for the error not to be buried in the logs? And should the script fail silently in this case?

2025-01-11 16:31 UTC, vvbandeira commented on tools/AutoTuner/src/autotuner/utils/plot.py
> +    p = np.poly1d(z)
`z` I assume is the z-axis; what is `p`?

2025-01-11 16:40 UTC, luarss commented on tools/AutoTuner/src/autotuner/utils/plot.py
> +            continue
> And should the script fail silently in this case?
Just to clarify, this exception happens when any Autotuner run does not proceed to the "finish" stage, it does not fail silently

> Should we keep a list of the files that were not processed so we can print them at the very end in order for the error not to be buried in the logs? 
Sure I can add that.

2025-01-11 16:41 UTC, luarss commented on tools/AutoTuner/src/autotuner/utils/plot.py
> +    p = np.poly1d(z)
`z` is the polynomial array of coefficients, and `p` is the actual polynomial function.

2025-01-11 23:07 UTC, vvbandeira commented on tools/AutoTuner/src/autotuner/utils/plot.py
> +    p = np.poly1d(z)
Then let's use more descriptive names, maybe:
`z` --> `coeff`
`p` --> `poly_func`

2025-01-11 23:11 UTC, vvbandeira commented on tools/AutoTuner/src/autotuner/utils/plot.py
> +    plt.savefig(f"images/{key}-boxplot.png")
Let's also parametrize the output folder to save images from CI into the reports folder for the design. This way it will be automatically saved to the build artifacts.

2025-01-12 16:36 UTC, vvbandeira requested changes

2025-01-12 16:36 UTC, vvbandeira commented on flow/test/test_autotuner.sh
> +    --design ${DESIGN_NAME} \
At the beginning of this script, you are casting these values to be uppercase, which does not match the path since Linux is case-sensitive. From the CI:
```
02:32:36  Running Autotuner plotting smoke test
02:32:36  ls: cannot access './flow/logs/SKY130HD/gcd/*/': No such file or directory
02:32:36  No experiments found for plotting
02:32:36  + exit 0
```

2025-01-12 16:37 UTC, vvbandeira commented on flow/test/test_autotuner.sh
> +    --design ${DESIGN_NAME} \
If we call the plot script and do not find data to plot, this should be an error, right?

2025-01-13 04:47 UTC, luarss commented on flow/test/test_autotuner.sh
> +    --design ${DESIGN_NAME} \
Yup, these are 2 separate errors, will fix them.

2025-01-15 16:14 UTC, vvbandeira requested changes

2025-01-15 16:14 UTC, vvbandeira commented on flow/test/test_autotuner.sh
> +if [ "$PLATFORM" == "asap7" ] && [ "$DESIGN_NAME" == "gcd" ]; then
The first check will never be true because you are casting to uppercase on line 14.
Would it be simpler/easier if we just use the platform name everywhere and just remove the dashes if that is not supported by the `unittest` Python lib?

2025-01-15 16:14 UTC, vvbandeira commented on flow/test/test_autotuner.sh
> +  exit 0
This is still exiting with a success code.

2025-01-15 16:14 UTC, vvbandeira commented on tools/AutoTuner/src/autotuner/utils/plot.py
> +        sys.exit(0)
This should also be an error and exit with non-zero value.

2025-01-15 16:14 UTC, vvbandeira commented on tools/AutoTuner/src/autotuner/utils/plot.py
> +        sys.exit(0)
Same as above.

2025-01-15 16:14 UTC, vvbandeira commented on tools/AutoTuner/src/autotuner/utils/plot.py
> +        sys.exit(0)
Same as above.

2025-01-16 02:21 UTC, luarss commented on flow/test/test_autotuner.sh
> +if [ "$PLATFORM" == "asap7" ] && [ "$DESIGN_NAME" == "gcd" ]; then
The main concern is that I want smoke tests to be capitalized. Perhaps a `UPPERCASE_PLATFORM` would make the distinction clearer?

2025-01-16 02:24 UTC, luarss commented on flow/test/test_autotuner.sh
> +  exit 0
This is returning 0 because I didn't want to error out for smoke tests that are not suitable for plotting. I will modify it to only run `plot.py` for valid smoke tests then.

2025-01-16 11:28 UTC, vvbandeira commented on flow/test/test_autotuner.sh
> +  exit 0
We could then change line 31 to list either manually the tests we want or use a better regex in the experiment names to differentiate whether the plot is available or not.

2025-01-16 11:28 UTC, vvbandeira commented on flow/test/test_autotuner.sh
> +if [ "$PLATFORM" == "asap7" ] && [ "$DESIGN_NAME" == "gcd" ]; then
Modifying PLATFORM or another variable already in use somewhere else in the code can easily lead to confusion. Other options could be `PLATFORM_UT` where UT is 'under test' or `TEST_PLATFORM`. That said, I don't see any issue with `asap7SampleIterationSmokeTest`.

2025-02-05 14:33 UTC, vvbandeira approved these changes

2025-02-05 20:21 UTC, merged