WIP: [Autotuner] Feature: add `--cpu_budget` and `--timeout_per_trial`
The-OpenROAD-Project/OpenROAD-flow-scripts pull request #2395
Opened 2024-09-29 10:26 UTC by luarss

Rationale
- More intuitive for end users who might just want to specify the total number of cpus to be blocked.
- `timeout_per_trial` is different from overall `timeout`. 

TODO
- [ ] Tests for `--cpu_budget` -> verify the actual number of cpus being used.
- [ ] Tests for timeout per trial and timeout -> does it actually stop the entire training?

2024-11-09 02:20 UTC, oharboe commented
The various ORFS stages have vastly different memory and CPU needs. 

How does the user  characterize and balance this?

2024-11-11 17:51 UTC, vvbandeira commented
> The various ORFS stages have vastly different memory and CPU needs.
> 
> How does the user characterize and balance this?

The intended usage for these knobs is to limit experiment runtime (and consequently $$ budget). These knobs do not limit how much resources a given ORFS run has access to.

CPU budget is intended to stop the experiment after the budget is spent.
Trial timeout will limit each ORFS complete flow runtime; this way, if your experiment requires 1k ORFS runs, you know you will, at most, use `1k * timout_per_trial` units of time.

2025-01-15 16:43 UTC, vvbandeira requested changes
Just an early feedback.

2025-01-15 16:43 UTC, vvbandeira commented on docs/user/InstructionsForAutoTuner.md
> +                       --yes \
We should prompt first users so that they know what is happening.

2025-01-15 16:43 UTC, vvbandeira commented on docs/user/InstructionsForAutoTuner.md
> +                       --yes \
Same as above.

2025-01-15 16:43 UTC, vvbandeira commented on tools/AutoTuner/src/autotuner/distributed.py
> +            ans = input("Are you sure you want to proceed? (y/n): ")
Add a print before this line or include in the input statement that the `-y/--yes` is available if the user does not wish to be asked again.

2025-01-22 01:20 UTC, luarss commented
@vvbandeira this PR is almost ready - just requires the fix from https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/2394 to be applied

2026-03-24 18:05 UTC, closed without merging