Update padding and grt adjustments for sky130 platforms
The-OpenROAD-Project/OpenROAD-flow-scripts pull request #241
Opened 2021-11-30 14:41 UTC by luis201420

2021-11-30 15:52 UTC, eder-matheus requested changes

2021-11-30 15:52 UTC, eder-matheus commented on flow/platforms/sky130hd/fastroute.tcl
> +#set_global_routing_layer_adjustment met1 0.4
You can remove these commented lines.

2021-11-30 15:52 UTC, eder-matheus commented on flow/platforms/sky130hs/fastroute.tcl
> +#set_global_routing_layer_adjustment met1 0.4
Same here, remove the commented lines.

2021-11-30 16:26 UTC, eder-matheus commented
@luis201420 These changes look good to me, but looking at the Google Sheet with the results of your experiments, it seems that running the GPL with timing_driven generates better results regarding time.
@maliberty do you think we should add it for the sky130 platforms?

2021-11-30 23:42 UTC, maliberty commented
Are only jpeg & aes affected by the change?  I don't see updates to the other metrics.

2021-12-01 22:14 UTC, eder-matheus commented
> Are only jpeg & aes affected by the change? I don't see updates to the other metrics.

We only changed these two designs because only they were failing. But yes, other designs are affected by the change. I can help Luis to update the metrics for them.

2021-12-10 00:39 UTC, maliberty commented
@luis201420 @eder-matheus any update?

2021-12-23 16:40 UTC, closed without merging