WIP [Autotuner] - Tunable variables check
The-OpenROAD-Project/OpenROAD-flow-scripts pull request #2452
Opened 2024-10-12 16:34 UTC by luarss

- [x] Tunable sanity check for autotuner
- [ ] Add yamllint
- [ ] Add tests
- [ ] Add CI
Fixes #2401

2024-10-13 08:05 UTC, oharboe requested changes
Lots of good stuff, some things to be addressed, break into several PRs, one for each concern(which will simplify reviews allow PRs to flow into master more smoothly)

2024-10-13 08:05 UTC, oharboe commented on docs/user/FlowVariables.md
> +| <a name="IO_CONSTRAINTS"></a>IO_CONSTRAINTS| File path to the IO constraints .tcl file.|  |
I propose not updating FlowVariables.md in pull requests that modify generate-variables-docs.py because it is likely to cause conflicts with other PRs in flight.

2024-10-13 08:05 UTC, oharboe commented on flow/scripts/generate-variables-docs.py
> +information about the variables from variables.yaml.
break out update to generate-variables-docs.py to separate PR, it has nothing to do with AutoTuner.

2024-10-13 08:05 UTC, oharboe commented on flow/scripts/generate-variables-docs.py
> +        raise FileNotFoundError(f"File {yaml_path} not found")
Interesting: why are you checking here instead of letting open() propagate this exception? What is the difference? 

Seems like this code should be removed, or at least it is very surprising and I have never seen it.

If there is a reason to keep it, it deserves a comment.

2024-10-13 08:05 UTC, oharboe commented on flow/util/utils.mk
> +get_tunable_variables:
why? Just read the .yaml file directly from distributed.py

2024-10-13 08:05 UTC, oharboe commented on flow/scripts/tunable.py
> +
why? Just read the .yaml file directly from distributed.py

2024-10-13 08:05 UTC, oharboe commented on tools/AutoTuner/src/autotuner/distributed.py
>      result = subprocess.run(["make", "vars", f"PLATFORM={args.platform}"])
why? Just read the .yaml file directly

2024-10-13 08:05 UTC, oharboe commented on flow/scripts/variables.yaml
> +  tunable: false
remove tunable: false, just set tunable: true for the few variables that are tunable.

2024-10-13 08:05 UTC, oharboe commented on flow/scripts/variables.yaml
> -  value: 1
Accidental removal?

2024-10-13 08:05 UTC, oharboe commented on flow/scripts/variables.yaml
> +  default: true
Nicely spotted, though keep it as 1, not "true".

2024-10-13 08:05 UTC, oharboe commented on flow/scripts/variables.yaml
> +  default: true
fix broken out in separate PR: https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/2455

2024-10-13 08:05 UTC, oharboe commented on tools/AutoTuner/src/autotuner/distributed.py
> +            if key not in flow_variables:
Change to:

if flow_variables.get(key, 0) != 1:

2024-10-13 08:05 UTC, oharboe commented on flow/scripts/variables.yaml
> +  tunable: false
use tcl idiomatic boolean values, tunable: 1/0.

2024-10-13 09:35 UTC, luarss commented on flow/scripts/generate-variables-docs.py
> +        raise FileNotFoundError(f"File {yaml_path} not found")
I usually try to write this to catch the exact exception triggering the open() error. Makes the code slightly verbose but easier to debug.

Also `yaml.safe_load()` might fail too (e.g. invalid yaml)

2024-10-13 10:08 UTC, oharboe commented on flow/scripts/generate-variables-docs.py
> +        raise FileNotFoundError(f"File {yaml_path} not found")
I think it is better to leave file not found to open(), it is what all other python code i have seen does: minimize surprises and questions in the code.

there is no evidence of specific unique circumstances here.

2024-10-15 13:18 UTC, oharboe reviewed
some comments during my ambling walk around ORFS...

2024-10-15 13:18 UTC, oharboe commented on tools/AutoTuner/src/autotuner/distributed.py
> +    with open("variables.yaml") as file:
don't use os.chdir(), use full paths instead.

2024-10-15 13:18 UTC, oharboe commented on tools/AutoTuner/src/autotuner/distributed.py
> +    os.chdir(initial_path)
os.chdir() is sure to end in tears. I advice against it.

2024-10-15 13:18 UTC, oharboe commented on tools/AutoTuner/src/autotuner/distributed.py
> +    vars_path = os.path.join(cur_path, "../../../../flow/scripts")
are you sure you want to use os.chdir() , why not use the path to the script as a reference instead?

2024-10-15 13:18 UTC, oharboe commented on docs/user/FlowVariables.md
> -
unstage changes to FlowVariables.md and let it be updated in standalone pull requests to update FlowVariables.md to minimize accidental pull request conflicts.

2024-10-19 07:32 UTC, oharboe reviewed
nits

2024-10-19 07:32 UTC, oharboe commented on tools/AutoTuner/src/autotuner/distributed.py
> +    variables = {key: 1 for key, value in result.items() if value.get("tunable") == 1}
this is effective a set, so use a set, easier to read the code

2024-10-19 07:32 UTC, oharboe commented on tools/AutoTuner/src/autotuner/distributed.py
> +            if flow_variables.get(key, 0) == 0:
use a set and "key in flow_variables", easier to read

2024-12-24 04:15 UTC, closed without merging