[Autotuner] Improve reliability 1
The-OpenROAD-Project/OpenROAD-flow-scripts pull request #2538
Opened 2024-10-31 18:36 UTC by luarss

2024-10-31 18:59 UTC, oharboe requested changes
have you considered python mocking to avoid processes that you have to start and stop?

2024-10-31 18:59 UTC, oharboe commented on tools/AutoTuner/Makefile
> +clearcache:
you need .PHONY target, or you are in for some subtle surprises

2024-11-01 02:55 UTC, luarss commented
> have you considered python mocking to avoid processes that you have to start and stop?

That is a good idea, I originally intended it to be as close to the real runtime environment as possible but if tests continue to fail this might be the move.

2024-11-01 06:11 UTC, oharboe commented
> > have you considered python mocking to avoid processes that you have to start and stop?
> 
> That is a good idea, I originally intended it to be as close to the real runtime environment as possible but if tests continue to fail this might be the move.

I'm thinking it is going to be both. I've been using bazel-orfs in an autotuner like capacity and the biggest problem I currently have is error handling and resource management. @jeffng-or and I launched an exploration run of, for instance, [MAX_UNGROUP_SIZE](https://github.com/The-OpenROAD-Project/megaboom/pull/191) and also we wanted to do the runs through grt.

The MAX_UNGROUP_SIZE never really completed, but I was able to look at the results that I got and I used them to plot the progress and the conclusion was trivial: there is no correct value of MAX_UNGROUP_SIZE, instead we have to first create a macro placement with SYNTH_HIERARCHICAL=1, but we have to throw away the result of that run and use that result in a run with SYNTH_HIERARCHICAL=0.

For the grt runs, the problem is that this part of the flow can't run in parallel with other runs, since it will then make the servers run out of memory and the servers will crash. I plan to fix bazel-orfs such that it has a rudimentary knowledge of which steps can run in parallel and which cannot. I think grt, route and macro placement have to run alone in a server, whereas the other stages can run in parallel. I need instrumentation in bazel-orfs to track the resident memory set to see what can run in parallel or not. Possibly I have to do a trial run from start to end, then track the memory requirements and CPU usage and come up with some sort of provisioning plan.

2025-01-09 10:18 UTC, vvbandeira commented on tools/AutoTuner/Makefile
> +.PHONY: init
```suggestion
.PHONY: clearcache init reqs test
```

2025-01-15 16:46 UTC, vvbandeira commented on tools/AutoTuner/installer.sh
> +    if pip3 cache purge && pip3 install --no-cache-dir -U -r "$script_dir/requirements.txt"; then
Is `cache purge` required with the `--no-cache-dir` option or are they redundant?

2025-01-21 13:00 UTC, luarss commented on tools/AutoTuner/installer.sh
> +    if pip3 cache purge && pip3 install --no-cache-dir -U -r "$script_dir/requirements.txt"; then
It's not mutually exclusive. Pip cache purge might be needed if system had cache before, and no cache dir just ensures no future caching is done.

2025-02-15 04:41 UTC, luarss commented
Opening a new PR for this.

2025-02-15 04:41 UTC, closed without merging