Split core function from user interface
The-OpenROAD-Project/OpenROAD-flow-scripts pull request #309
Opened 2022-01-12 12:48 UTC by suzizecat

Hi,

This merge request aim to split the mergeLef file into a function (that might be imported in other python scripts) and a user interface (parameter parsing) used when the file is used as standalone. 

This could allow other flow tools interacting with OpenROAD to easily use mergeLef.

Best regards,
Julien FAUCHER

2022-01-12 16:41 UTC, maliberty requested changes
I'm curious what other purpose you intend to use this script for.

2022-01-12 16:41 UTC, maliberty commented on flow/util/mergeLef.py
> +def mergeLef(inputLef,outputLef) :
Please put a space after the comma per PEP8

2022-01-12 16:41 UTC, maliberty commented on flow/util/mergeLef.py
> +  mergeLef(args.inputLef,args.outputLef)
Please put a space after the comma per PEP8

2022-01-12 16:48 UTC, suzizecat commented
The purpose might be easier interfacing when using SiliconCompiler since it looks like OpenROAD needs tlef and lef to be merged. Therefore it would be easier to be able to just import the the mergeLef function rather than spawning a whole new process for this.

2022-01-12 17:05 UTC, maliberty approved these changes

2022-01-12 17:06 UTC, maliberty commented
The mergeLef is a holdover from standalone TritonRoute.  It isn't needed anymore or used afaik.

2022-01-12 22:54 UTC, rovinski commented
Correct, MergeLef isn't used anywhere in the flow. I thought it was already removed.

2022-03-02 20:18 UTC, tspyrou commented
@suzizecat can you merge in the changes in master to your branch. Hopefully that will fix the CI failure.

2022-03-02 21:04 UTC, maliberty commented
@tspyrou I don't see any reason to merge this - we should just remove mergeLef as it is obsolete

2022-06-13 17:22 UTC, maliberty commented
Removed mergeLef in https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/484

2022-06-13 17:22 UTC, closed without merging