asap7: Add MIN_CLOCK_ROUTING_LAYER
The-OpenROAD-Project/OpenROAD-flow-scripts pull request #564
Opened 2022-08-21 22:20 UTC by antonblanchard

Use higher metal layers for clock routing.

Signed-off-by: Anton Blanchard <anton@linux.ibm.com>

2022-08-21 22:27 UTC, antonblanchard commented
I solved this in a platform specific way. Do we want the generic scripts to handle optional min/max clock routing layers?

2022-08-22 22:44 UTC, maliberty requested changes

2022-08-22 22:44 UTC, maliberty commented on flow/platforms/asap7/config.mk
> +export FASTROUTE_TCL ?= $(PLATFORM_DIR)/fastroute.tcl
I don't think this is necessary.  In global_route.tcl just check if MIN_CLOCK_ROUTING_LAYER  is defined and if so do

set_routing_layers -clock $env(MIN_CLOCK_ROUTING_LAYER)-$env(MAX_ROUTING_LAYER)

2022-08-22 22:44 UTC, maliberty commented on flow/platforms/asap7/fastroute.tcl
> +set_macro_extension 2
remove this file

2023-01-16 16:46 UTC, maliberty commented
@antonblanchard I believe this is pending on action from you but I'm not certain

2025-02-18 01:46 UTC, maliberty commented
stale, better to use clock NDRs

2025-02-18 01:46 UTC, closed without merging