logging build
The-OpenROAD-Project/OpenROAD-flow-scripts pull request #666
Opened 2022-12-02 00:04 UTC by habibayassin

Signed-off-by: habibayassin <habibayassin@aucegypt.edu>

2022-12-02 14:03 UTC, vvbandeira requested changes
can you also modify the Jenkinsfiles to save the build log as an artifact? Might prove useful when CI fails to build for any reason.

2022-12-02 14:03 UTC, vvbandeira commented on build_openroad.sh
> +
Should this be at the top of the file to catch all messages? Or, to avoid conflicts with the git clean, we should refactor the steps above into a bash function and orchestrate the flow to do cleanup, start the log, and then build. To try and catch as much as possible from the output.

2022-12-02 14:03 UTC, vvbandeira commented on build_openroad.sh
> +{
Just me nitpicking, do not add white spaces at the end of lines.

2022-12-02 14:03 UTC, vvbandeira commented on build_openroad.sh
> +        rm -rf "${buildDir}"
I don't think we need to delete the build dir. The git clean command should control that.

2022-12-02 22:02 UTC, habibayassin commented on build_openroad.sh
> +
I pushed some changes please let me know if that's what you had in mind

2022-12-02 22:39 UTC, rovinski commented on build_openroad.sh
> +        exec > >(tee -i ${buildDir}/build-$(date +%s).log)
Hmmm, I was only thinking about saving the most recent build log. It seems like most users won't need to save multiple logs. On the other hand, saving logs doesn't hurt much. @vvbandeira can decide.

2022-12-05 16:08 UTC, vvbandeira commented on build_openroad.sh
> +
Almost. I already had a branch with these changes locally so I just merged our changes.

2022-12-05 16:10 UTC, vvbandeira commented on build_openroad.sh
> +        exec > >(tee -i ${buildDir}/build-$(date +%s).log)
At first, I thought it would be nice to have multiple logs, but that will also add the possibility of the user submitting the wrong log. So let's keep only the latest to simplify things.

2022-12-05 16:11 UTC, vvbandeira commented
@habibayassin I think the only change needed is in the Jenkinsfiles to save the log as an artifact. Other than that it looks good to merge.

2022-12-05 23:58 UTC, vvbandeira approved these changes

2022-12-07 11:55 UTC, merged