Dep Installer: update documentation
The-OpenROAD-Project/OpenROAD-flow-scripts pull request #853
Opened 2023-03-07 15:37 UTC by habibayassin

2023-03-07 16:36 UTC, vvbandeira commented
@vijayank88 FYI

2023-03-07 16:46 UTC, vvbandeira requested changes

2023-03-07 16:46 UTC, vvbandeira commented on docs/user/BuildLocally.md
> +## Clona and Install Dependencies
```suggestion
## Clone and Install Dependencies
```

2023-03-07 16:46 UTC, vvbandeira commented on docs/user/BuildLocally.md
> +The DependencyInstaller script installs all of the dependencies including OpenROAD dependencies if they are not already installed.
```suggestion
The 1DependencyInstaller.sh` script installs all of the dependencies, including OpenROAD dependencies, if they are not already installed.
```

2023-03-07 16:46 UTC, vvbandeira commented on docs/user/BuildWithDocker.md
> +### Build image generally
```suggestion
### Build Docker image
```

2023-03-07 16:46 UTC, vvbandeira commented on docs/user/BuildWithDocker.md
> +Build stage actually builds all of the binaries needed to run flows.
```suggestion
The following instructions build the docker image with a parameterized OS in two stages. 
Dev stage for installing all the dependencies and packages that are needed to run OpenROAD and OpenROAD Flow Scripts.
The build stage actually builds all of the binaries needed to run flow (i.e., `openroad` and `yosys`).
```

2023-03-07 16:46 UTC, vvbandeira commented on docs/user/BuildWithDocker.md
> +
```suggestion
### Build image with default values

The following instructions build the docker image with Centos 7 as the base OS:

```

2023-03-09 09:06 UTC, vijayank88 commented
@vvbandeira 
Can you please check why its failing during docker build with CI?
Please merge the document update ASAP, as people still referring old docs and facing issue during installation.

2023-03-09 12:10 UTC, vvbandeira approved these changes

2023-03-09 12:11 UTC, merged