bump or submodule
The-OpenROAD-Project/OpenROAD-flow-scripts pull request #908
Opened 2023-03-21 13:58 UTC by vvbandeira

asap7/aes base
[INFO] Tightening rule placeopt__design__instance__area from 2874 to 2871.
[INFO] Tightening rule globalroute__timing__clock__slack from -70.89 to -70.51.
[INFO] Tightening rule globalroute__timing__setup__ws from -70.89 to -70.51.
[INFO] Updating failing rule finish__timing__setup__ws from -20.0 to -51.87.

asap7/ethmac base
[INFO] Tightening rule detailedroute__route__wirelength from 250905 to 250821.
[INFO] Updating failing rule finish__timing__setup__ws from -26.5 to -56.14.

2023-03-21 16:28 UTC, vvbandeira commented on flow/designs/asap7/mock-array-big/Element/io.tcl
> +    set_io_pin_constraint -region $direction:* -pin_names [lindex $names 0] -order
@oharboe FYI, I saw you changed this recently. Let me know if the fix should be different.

2023-03-21 18:33 UTC, oharboe commented on flow/designs/asap7/mock-array-big/Element/io.tcl
> +    set_io_pin_constraint -region $direction:* -pin_names [lindex $names 0] -order
I've updated the PR again: https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/905

Hopefully I got it right this time.

2023-03-22 16:23 UTC, maliberty approved these changes

2023-03-22 16:28 UTC, oharboe requested changes
This won't work  https://github.com/The-OpenROAD-Project/OpenROAD/issues/3055 is fixed.

After that, rebase and squash (to have a single commit that fixes the use of -group and -order).

2023-03-22 17:20 UTC, merged