helper: script to set up paths to locally built tools
The-OpenROAD-Project/OpenROAD-flow-scripts pull request #928
Opened 2023-03-29 05:55 UTC by oharboe

2023-03-31 19:20 UTC, vvbandeira requested changes
Thanks for the contribution. Just a suggestion to wrap variables in quotes to consider if any folder in the path has a space.

2023-03-31 19:20 UTC, vvbandeira commented on setup.sh
> +sudo -u $SUDO_USER $DIR/tools/OpenROAD/etc/DependencyInstaller.sh -common -prefix=$DIR/dependencies
```suggestion
"$DIR/tools/OpenROAD/etc/DependencyInstaller.sh" -base

sudo -u $SUDO_USER "$DIR/tools/OpenROAD/etc/DependencyInstaller.sh" -common -prefix="$DIR/dependencies"
```

2023-03-31 19:20 UTC, vvbandeira commented on dev_env.sh
> +    export PATH=$DIR/dependencies/bin:$PATH
```suggestion
    export PATH="$DIR/dependencies/bin:$PATH"
```

2023-03-31 20:01 UTC, oharboe commented on setup.sh
> +sudo -u $SUDO_USER $DIR/tools/OpenROAD/etc/DependencyInstaller.sh -common -prefix=$DIR/dependencies
Makes sense, but did you try it? I worry about the -prefix bit, shouldnt that be quotes around the entire argument?

2023-04-01 06:40 UTC, oharboe commented
@vvbandeira Tested your changes. Worked fine!

2023-04-01 13:53 UTC, oharboe commented
@maliberty Build server problems, false positive.

2023-04-01 14:15 UTC, maliberty commented
@vvbandeira is looking at it. Seems like out of disk space

2023-04-01 16:18 UTC, oharboe commented
> @vvbandeira is looking at it. Seems like out of disk space

👍 Classic.

2023-04-03 10:31 UTC, vvbandeira approved these changes

2023-04-03 10:31 UTC, merged

2023-04-03 10:42 UTC, oharboe commented
@vvbandeira Thanks!

2023-04-03 11:06 UTC, vijayank88 commented
@vvbandeira 
Due to confusion raising this question.
Now with `setup.sh` required packages installed from `tools/OpenROAD/etc/DependecyInstaller.sh`.
But it is different from `OpenROAD-flow-scripts/etc/DependencyInstaller.sh` right?
Because ORFS flow installer script will do KLayout installation also part of the script. But not `./setup.sh` right?

2023-04-03 11:25 UTC, oharboe commented
> @vvbandeira Due to confusion raising this question. Now with `setup.sh` required packages installed from `tools/OpenROAD/etc/DependecyInstaller.sh`. But it is different from `OpenROAD-flow-scripts/etc/DependencyInstaller.sh` right? Because ORFS flow installer script will do KLayout installation also part of the script. But not `./setup.sh` right?

Like so?

https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/949