using :?operator cts file is updated
The-OpenROAD-Project/OpenROAD-flow-scripts pull request #930
Opened 2023-03-29 16:28 UTC by Divya342

2023-03-29 16:55 UTC, maliberty requested changes
Thanks for contributing.  A few changes are required.  Also please see the DCO details link for information on fixing it.

2023-03-29 16:55 UTC, maliberty commented on flow/scripts/cts.tcl
> +#change ifelse to :?
No need for this comment

2023-03-29 16:55 UTC, maliberty commented on input and output operations
Do not rename

2023-03-30 14:29 UTC, maliberty commented
You are mixing all sorts of changes together.  Is this a PR that you expect to merge or just personal work?

2023-03-30 16:02 UTC, rovinski commented
I too am confused about the purpose of this PR.

2023-03-30 18:33 UTC, closed without merging