Clean up/extend mock-array-big
The-OpenROAD-Project/OpenROAD-flow-scripts pull request #955
Opened 2023-04-04 11:56 UTC by yupferris

Currently doesn't build; issue incoming.

2023-04-05 06:36 UTC, oharboe approved these changes

2023-04-05 06:36 UTC, oharboe commented on flow/designs/src/mock-array-big/src/test/scala/MockArray.scala
> +      a.io.ins.asSeq(Routes.LEFT.id) := b.io.outs.asSeq(Routes.LEFT.id)
@yupferris Just a thought for next crossroads, change to asMap() so that we can specify Routes.LEFT instead of Routes.LEFT.id?

2023-04-05 06:48 UTC, yupferris commented on flow/designs/src/mock-array-big/src/test/scala/MockArray.scala
> +      a.io.ins.asSeq(Routes.LEFT.id) := b.io.outs.asSeq(Routes.LEFT.id)
Thanks for the tip!

2023-04-11 10:57 UTC, oharboe requested changes
Make the Verilog prettier: https://scastie.scala-lang.org/8Riy7YqEQ3yAOztcgcZPbA

2023-04-14 13:33 UTC, oharboe requested changes
break out a PR with everything that is ready to go in that doesn't relate to complicated topics like timing.

2023-04-14 14:18 UTC, oharboe approved these changes
Nit: later we can greatly simplify the io.tcl files by using regular expressions instead of this more tedious enumeration. With regex we don't need to bring in the dimensions and datapath widths to io.tcl files...

2023-04-14 14:22 UTC, yupferris commented
@maliberty this should be ready to go in, which would be nice as I have a future PR with timing (#986) to go in after this.

2023-04-17 08:13 UTC, yupferris commented
@maliberty The build seems to be failing with this error:
```
[ERROR] synth__design__instance__area__stdcell fail test: 0.04374 <= 0.0
```

What does this mean? How do I fix it?

2023-04-17 08:56 UTC, vijayank88 commented
@yupferris 
If metrics report valid with local test, you can update the metrics by `make update_ok` to pass CI.

Refer this tutorial for updating the reference files : https://openroad-flow-scripts.readthedocs.io/en/latest/user/FAQS.html#how-do-i-update-the-design-reference-files

2023-04-17 09:05 UTC, yupferris commented
@vijayank88 Thanks for the reply. I thought that might be the case after [the last time you clarified that for me](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/934#issuecomment-1491919653), so I've already done that in https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/955/commits/b8d8fd7c07644488a5ca70b060c4da842a042ce2, yet it still appears to be failing.

2023-04-17 09:25 UTC, vijayank88 commented
@vvbandeira 
Can you check this?

2023-04-19 17:37 UTC, vvbandeira commented
@yupferris please merge the latest master into your dev branch and run `make update_ok` again for the desired design.

2023-04-20 08:24 UTC, yupferris commented
@vvbandeira looks like that did it, cheers!

2023-04-20 11:39 UTC, yupferris commented
@maliberty this one should be ready for review/merge now.

2023-04-20 22:37 UTC, maliberty approved these changes

2023-04-20 22:37 UTC, merged